/**
 * Drizzle schema for the PDF Forge database (PostgreSQL 15 / Supabase).
 *
 * Conventions:
 *   - Snake_case for column names; camelCase for TS field names.
 *   - All `id` columns are UUID v4 generated by Postgres (`gen_random_uuid()`).
 *   - All `created_at` / `updated_at` columns are `timestamptz` with default `now()`.
 *   - Enums are declared via `pgEnum` so they're real Postgres enums (not check constraints).
 *   - Every foreign key spells out `onDelete`/`onUpdate` explicitly.
 *   - Indexes are co-located with each table for discoverability.
 */

import { relations, type InferInsertModel, type InferSelectModel } from 'drizzle-orm';
import {
  bigint,
  boolean,
  char,
  date,
  index,
  integer,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

/* ─────────────────────────────────────────────────────────────────
 * Enums
 * ──────────────────────────────────────────────────────────────── */

export const subscriptionPlanEnum = pgEnum('subscription_plan', [
  'free',
  'premium_monthly',
  'premium_yearly',
  'business',
]);

export const subscriptionStatusEnum = pgEnum('subscription_status', [
  'active',
  'cancelled',
  'expired',
  'past_due',
]);

export const operationStatusEnum = pgEnum('operation_status', [
  'started',
  'processing',
  'completed',
  'failed',
]);

export const paymentStatusEnum = pgEnum('payment_status', ['success', 'failed', 'refunded']);

export const blogPostStatusEnum = pgEnum('blog_post_status', ['draft', 'published', 'archived']);

/* ─────────────────────────────────────────────────────────────────
 * users
 * ──────────────────────────────────────────────────────────────── */

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clerkId: varchar('clerk_id', { length: 255 }).notNull().unique(),
    email: varchar('email', { length: 320 }).notNull().unique(),
    name: varchar('name', { length: 255 }),
    avatarUrl: text('avatar_url'),
    country: char('country', { length: 2 }),
    phone: varchar('phone', { length: 32 }),
    emailVerified: boolean('email_verified').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    isActive: boolean('is_active').notNull().default(true),
  },
  (table) => ({
    emailVerifiedIdx: index('users_email_verified_idx').on(table.emailVerified),
    isActiveIdx: index('users_is_active_idx').on(table.isActive),
    lastLoginAtIdx: index('users_last_login_at_idx').on(table.lastLoginAt),
    createdAtIdx: index('users_created_at_idx').on(table.createdAt),
  }),
);

export type User = InferSelectModel<typeof users>;
export type NewUser = InferInsertModel<typeof users>;

/* ─────────────────────────────────────────────────────────────────
 * subscriptions
 * ──────────────────────────────────────────────────────────────── */

export const subscriptions = pgTable(
  'subscriptions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
    plan: subscriptionPlanEnum('plan').notNull().default('free'),
    status: subscriptionStatusEnum('status').notNull().default('active'),
    razorpaySubscriptionId: varchar('razorpay_subscription_id', { length: 255 }),
    razorpayCustomerId: varchar('razorpay_customer_id', { length: 255 }),
    currentPeriodStart: timestamp('current_period_start', { withTimezone: true }),
    currentPeriodEnd: timestamp('current_period_end', { withTimezone: true }),
    cancelAtPeriodEnd: boolean('cancel_at_period_end').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index('subscriptions_user_id_idx').on(table.userId),
    statusIdx: index('subscriptions_status_idx').on(table.status),
    planIdx: index('subscriptions_plan_idx').on(table.plan),
    currentPeriodEndIdx: index('subscriptions_current_period_end_idx').on(table.currentPeriodEnd),
    razorpaySubscriptionIdUnique: uniqueIndex('subscriptions_razorpay_sub_id_unique').on(
      table.razorpaySubscriptionId,
    ),
  }),
);

export type Subscription = InferSelectModel<typeof subscriptions>;
export type NewSubscription = InferInsertModel<typeof subscriptions>;

/* ─────────────────────────────────────────────────────────────────
 * operations
 * ──────────────────────────────────────────────────────────────── */

export const operations = pgTable(
  'operations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').references(() => users.id, {
      onDelete: 'set null',
      onUpdate: 'cascade',
    }),
    anonymousId: varchar('anonymous_id', { length: 64 }),
    toolSlug: varchar('tool_slug', { length: 100 }).notNull(),
    status: operationStatusEnum('status').notNull().default('started'),
    inputFilesCount: integer('input_files_count').notNull().default(0),
    inputSizeBytes: bigint('input_size_bytes', { mode: 'number' }).notNull().default(0),
    outputSizeBytes: bigint('output_size_bytes', { mode: 'number' }),
    outputFileUrl: text('output_file_url'),
    outputFileExpiresAt: timestamp('output_file_expires_at', { withTimezone: true }),
    errorMessage: text('error_message'),
    processingTimeMs: integer('processing_time_ms'),
    ipAddress: varchar('ip_address', { length: 45 }),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index('operations_user_id_idx').on(table.userId),
    anonymousIdIdx: index('operations_anonymous_id_idx').on(table.anonymousId),
    toolSlugIdx: index('operations_tool_slug_idx').on(table.toolSlug),
    statusIdx: index('operations_status_idx').on(table.status),
    createdAtIdx: index('operations_created_at_idx').on(table.createdAt),
    userToolCreatedIdx: index('operations_user_tool_created_idx').on(
      table.userId,
      table.toolSlug,
      table.createdAt,
    ),
    expiresAtIdx: index('operations_expires_at_idx').on(table.outputFileExpiresAt),
  }),
);

export type Operation = InferSelectModel<typeof operations>;
export type NewOperation = InferInsertModel<typeof operations>;

/* ─────────────────────────────────────────────────────────────────
 * payments
 * ──────────────────────────────────────────────────────────────── */

export const payments = pgTable(
  'payments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
    subscriptionId: uuid('subscription_id').references(() => subscriptions.id, {
      onDelete: 'set null',
      onUpdate: 'cascade',
    }),
    amountInr: numeric('amount_inr', { precision: 10, scale: 2 }).notNull(),
    currency: char('currency', { length: 3 }).notNull().default('INR'),
    status: paymentStatusEnum('status').notNull(),
    razorpayPaymentId: varchar('razorpay_payment_id', { length: 255 }).notNull().unique(),
    razorpayOrderId: varchar('razorpay_order_id', { length: 255 }),
    invoiceNumber: varchar('invoice_number', { length: 64 }),
    invoiceUrl: text('invoice_url'),
    paymentMethod: varchar('payment_method', { length: 64 }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index('payments_user_id_idx').on(table.userId),
    subscriptionIdIdx: index('payments_subscription_id_idx').on(table.subscriptionId),
    statusIdx: index('payments_status_idx').on(table.status),
    razorpayOrderIdIdx: index('payments_razorpay_order_id_idx').on(table.razorpayOrderId),
    createdAtIdx: index('payments_created_at_idx').on(table.createdAt),
    invoiceNumberUnique: uniqueIndex('payments_invoice_number_unique').on(table.invoiceNumber),
  }),
);

export type Payment = InferSelectModel<typeof payments>;
export type NewPayment = InferInsertModel<typeof payments>;

/* ─────────────────────────────────────────────────────────────────
 * usage_tracking
 *
 * Aggregates daily counters per user OR per anonymous visitor.
 * Two partial unique indexes guarantee one row per (user_id, date)
 * AND one row per (anonymous_id, date) — Postgres treats NULLs as
 * distinct, so the indexes only constrain non-null subsets.
 * ──────────────────────────────────────────────────────────────── */

export const usageTracking = pgTable(
  'usage_tracking',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').references(() => users.id, {
      onDelete: 'cascade',
      onUpdate: 'cascade',
    }),
    anonymousId: varchar('anonymous_id', { length: 64 }),
    date: date('date', { mode: 'string' }).notNull(),
    operationsCount: integer('operations_count').notNull().default(0),
    bytesProcessed: bigint('bytes_processed', { mode: 'number' }).notNull().default(0),
  },
  (table) => ({
    userDateUnique: uniqueIndex('usage_tracking_user_date_unique').on(table.userId, table.date),
    anonDateUnique: uniqueIndex('usage_tracking_anon_date_unique').on(
      table.anonymousId,
      table.date,
    ),
    dateIdx: index('usage_tracking_date_idx').on(table.date),
    userIdIdx: index('usage_tracking_user_id_idx').on(table.userId),
  }),
);

export type UsageTracking = InferSelectModel<typeof usageTracking>;
export type NewUsageTracking = InferInsertModel<typeof usageTracking>;

/* ─────────────────────────────────────────────────────────────────
 * api_keys
 * ──────────────────────────────────────────────────────────────── */

export const apiKeys = pgTable(
  'api_keys',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
    keyHash: varchar('key_hash', { length: 128 }).notNull().unique(),
    name: varchar('name', { length: 100 }).notNull(),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
  },
  (table) => ({
    userIdIdx: index('api_keys_user_id_idx').on(table.userId),
    isActiveIdx: index('api_keys_is_active_idx').on(table.isActive),
    expiresAtIdx: index('api_keys_expires_at_idx').on(table.expiresAt),
  }),
);

export type ApiKey = InferSelectModel<typeof apiKeys>;
export type NewApiKey = InferInsertModel<typeof apiKeys>;

/* ─────────────────────────────────────────────────────────────────
 * blog_posts
 * ──────────────────────────────────────────────────────────────── */

export const blogPosts = pgTable(
  'blog_posts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    slug: varchar('slug', { length: 255 }).notNull().unique(),
    title: varchar('title', { length: 255 }).notNull(),
    excerpt: text('excerpt'),
    content: text('content').notNull(),
    coverImageUrl: text('cover_image_url'),
    authorId: uuid('author_id').references(() => users.id, {
      onDelete: 'set null',
      onUpdate: 'cascade',
    }),
    status: blogPostStatusEnum('status').notNull().default('draft'),
    metaTitle: varchar('meta_title', { length: 255 }),
    metaDescription: varchar('meta_description', { length: 320 }),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    viewsCount: integer('views_count').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    authorIdIdx: index('blog_posts_author_id_idx').on(table.authorId),
    statusIdx: index('blog_posts_status_idx').on(table.status),
    publishedAtIdx: index('blog_posts_published_at_idx').on(table.publishedAt),
    statusPublishedIdx: index('blog_posts_status_published_idx').on(
      table.status,
      table.publishedAt,
    ),
  }),
);

export type BlogPost = InferSelectModel<typeof blogPosts>;
export type NewBlogPost = InferInsertModel<typeof blogPosts>;

/* ─────────────────────────────────────────────────────────────────
 * Relations
 * ──────────────────────────────────────────────────────────────── */

export const usersRelations = relations(users, ({ many }) => ({
  subscriptions: many(subscriptions),
  operations: many(operations),
  payments: many(payments),
  apiKeys: many(apiKeys),
  blogPosts: many(blogPosts),
  usageTracking: many(usageTracking),
}));

export const subscriptionsRelations = relations(subscriptions, ({ one, many }) => ({
  user: one(users, {
    fields: [subscriptions.userId],
    references: [users.id],
  }),
  payments: many(payments),
}));

export const operationsRelations = relations(operations, ({ one }) => ({
  user: one(users, {
    fields: [operations.userId],
    references: [users.id],
  }),
}));

export const paymentsRelations = relations(payments, ({ one }) => ({
  user: one(users, {
    fields: [payments.userId],
    references: [users.id],
  }),
  subscription: one(subscriptions, {
    fields: [payments.subscriptionId],
    references: [subscriptions.id],
  }),
}));

export const usageTrackingRelations = relations(usageTracking, ({ one }) => ({
  user: one(users, {
    fields: [usageTracking.userId],
    references: [users.id],
  }),
}));

export const apiKeysRelations = relations(apiKeys, ({ one }) => ({
  user: one(users, {
    fields: [apiKeys.userId],
    references: [users.id],
  }),
}));

export const blogPostsRelations = relations(blogPosts, ({ one }) => ({
  author: one(users, {
    fields: [blogPosts.authorId],
    references: [users.id],
  }),
}));

/* ─────────────────────────────────────────────────────────────────
 * Convenience: full schema export for `drizzle({ schema })`
 * ──────────────────────────────────────────────────────────────── */

export const schema = {
  users,
  subscriptions,
  operations,
  payments,
  usageTracking,
  apiKeys,
  blogPosts,

  usersRelations,
  subscriptionsRelations,
  operationsRelations,
  paymentsRelations,
  usageTrackingRelations,
  apiKeysRelations,
  blogPostsRelations,

  subscriptionPlanEnum,
  subscriptionStatusEnum,
  operationStatusEnum,
  paymentStatusEnum,
  blogPostStatusEnum,
} as const;

export type Schema = typeof schema;
